moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller
    - base_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - Gripper_Servo_Gear_Joint
      - Gripper_Idol_Gear_Joint

  # 🔥 ADD THIS BLOCK
  base_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - planar_joint/x
      - planar_joint/y
      - planar_joint/theta