ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom



    # rf2o position only
    odom0: /odom_rf2o
    odom0_differential: false
    odom0_relative: false

    odom0_config: [
      true,  true,  false,   # x, y
      false, false, false,   # roll pitch yaw ❌
      true,  true,  false,   # vx vy
      false, false, false
    ]

    # IMU orientation only
    imu0: /imu/data_raw
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_nodelay: false
    imu0_config: [
      false, false, false,   # x y z position ❌
      true,  true,  false,   # roll pitch ✔ yaw ❌
      false, false, false,   # vx vy vz ❌
      true,  true,  false     # roll_rate pitch_rate yaw_rate ✔
    ]


    imu0_remove_gravitational_acceleration: true
